### ISSUE TITLE
Broken in core version 0.7.9

### ISSUE THREAD

**Issue by ScottMaclure** [voidcase/IntoTheOdd-FoundryVTT#12]
- Flagged as compatibility risk
- When creating a Scene or an Actor, couldn't edit the "Name" field (and so couldn't create them)

**Comment by voidcase** [comment]
@ScottMaclure I am on 0.7.9 and I can not reproduce the issue. Are you getting any errors or anything in the js log? (F12)

**Comment by ScottMaclure** [comment]
I created a new game world after updating the ItO game system, and can't reproduce the problem.
