### ISSUE TITLE
Into the Odd Game System incompatible with Foundry VTT 0.8.6

### ISSUE THREAD

**Issue by Lim-Dul** [voidcase/IntoTheOdd-FoundryVTT#16]
**Observed Behavior**
After creating a new Actor in FVTT 0.8.6, any values entered on the character sheet, including in items, fail to save and all fields get reset.
Also the section for base attributes is not displayed altogether.

**Expected Behavior**
After creating a new Actor in FVTT 0.8.6, any values entered on the character sheet are properly saved and the base attribute section is displayed.

**Steps to Reproduce**
1. Create a new world in FVTT 0.8.6 using Into the Odd as Game System
2. Launch the new world as Gamemaster
3. Create a new actor e.g. named Test
4. Open the new actor and attempt to enter values into hitpoints or item statistics after adding an item; also observe the missing base attribute section

![image](https://user-images.githubusercontent.com/428324/121888604-7c1b3880-cd18-11eb-892e-4fc8ca85b847.png)

**Comment by voidcase** [comment]
I've started looking at this now.

- I've gotten the values to show up in the sheet, but they still don't want to be updated. No error is shown in the console when I try.
- Owned items should not be handled with the now deprecated `getOwnedItem()` and it's siblings

**Comment by Lim-Dul** [comment]
I think there might be a hint in other module updates. Mausritter, Mörk Borg and I believe Knave had similar problems but they fixed them. Oh, let's not forget Electric Bastionland.
Also, Cairn (unsurprisingly) has this problem at the moment but the lads and lassies over there have a semi-working version, I believe.

**Comment by voidcase** [comment]
Thanks to reading the update commit from the EB module repo, I have now managed to make the fields visible and editable. Now it's only items and rolls left (and maybe more broken things I don't know about yet)

**Comment by voidcase** [comment]
Alright, item handling seems fixed now! On to the rolls.
Work on this issue is done on [this branch](https://github.com/voidcase/IntoTheOdd-FoundryVTT/tree/compat_0.8.7)

**Comment by voidcase** [comment]
just updated to 0.8.8, and the sheets broke again... yay...

**Comment by voidcase** [comment]
False alarm, I was just on the wrong branch. Thought I was going crazy there for a sec, lol.

**Comment by voidcase** [comment]
version 1.2.0, compatible with foundryvtt 8.8.0 is now out :)

**Comment by Lim-Dul** [comment]
Works like a charm. Tested on FoundryVTT 0.8.8 with all modules disabled.
Attributes are displayed and can be saved, item workflow works as expected.
![image](https://user-images.githubusercontent.com/428324/124095394-ea226800-da59-11eb-99f1-bdebb468436d.png)
