### ISSUE TITLE
Update to Into The Odd Remastered

### ISSUE THREAD

**Issue by voidcase** [voidcase/IntoTheOdd-FoundryVTT#32]
A remastered version is out, and the old version is out of print, so it is only fitting that this module is updated to reflect the new.

The notable changes that come with the remastered version of the game are:

* [x] adding a "deprived" boolean flag to character sheet
* [x] replacing the "hands" item attribute with a boolean "bulky"
* [x] changing CSS to match the look and feel of the remastered book rather than the old book.

**Comment by Qaw** [comment]
I got the remastered version but I don't have the old version.
If you can list all the changes in this issue.
Do you think the system should evolve to new one as new player won't have the out of print version ?
Do we need to be compatible with both ?

**Comment by voidcase** [comment]
@Qaw We should definitely evolve to support the new version, and I don't think we need to keep explicit compatibility with the old version. It should be fine to use with the old one anyway.

**Comment by Qaw** [comment]
Will be done in 2.0.0 version
