### ISSUE TITLE
Investigate and get rid of strange deprecation warnings before Foundry V12

### ISSUE THREAD

**Issue by voidcase** [voidcase/IntoTheOdd-FoundryVTT#33]
We are getting warnings like these since v10:

> Error: You are accessing the IntoTheOddItem#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.

I thought I had removed all references to the data object, but I am still getting the warnings from somewhere. It would be greatly appreciated if someone could  investigate why this is happening so the module doesn't break in v12

for reference: https://github.com/foundryvtt/foundryvtt/issues/6849

**Comment by Qaw** [comment]
When do you have this message ?
In Foundry v10 with wich version of the system ?

**Comment by voidcase** [comment]
I vaguely remember it happening when you add an item in an actors inventory. If you cannot reproduce it you can close this issue.

**Comment by Qaw** [comment]
Cannot reproduce
