### ISSUE TITLE
Getting an error when trying to install

### ISSUE THREAD

**Issue by anmej** [voidcase/IntoTheOdd-FoundryVTT#46]
I'm getting this error:
"Unable to load valid system manifest data from "https://raw.githubusercontent.com/voidcase/IntoTheOdd-FoundryVTT/v1.3.1/system.json" System validation error: packs: 0 type: may not be undefined|"

**Comment by BatmanTheBlind** [comment]
Just ran into the same issue, it seems there's a pull request on the system to be compatible with V11 : https://github.com/voidcase/IntoTheOdd-FoundryVTT/pull/45

Not sure about the procedure to manually install a module from it though

**Comment by Qaw** [comment]
Version 1.4.0 is v11 compatible
